#!/usr/bin/bash

freq=`sudo intel_gpu_frequency | grep cur | cut -d' ' -f2`
if [ "$freq" -eq 300 ]
 then newfreq=1050
fi
if [ "$freq" -gt 300 ]
 then newfreq=300
fi

sudo intel_gpu_frequency -c max=$newfreq
