#!/usr/bin/bash

echo 1 | tee /sys/devices/system/cpu/intel_pstate/no_turbo
echo 1000000 | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq 
intel_gpu_frequency -i
smm 30a3
echo "-- USE AT OWN RISK, LAPTOP MAY OVERHEAT! --"







